head:
   favicon: "https://s1.ax1x.com/2022/03/28/qD7Sdx.jpg" #  the favicon
   high_res_favicon: "https://s1.ax1x.com/2022/03/28/qD7Sdx.jpg" #  the favicon using high quality format
   apple_touch_icon: "https://ooo.0o0.ooo/2017/06/08/5939484dc618e.png" # the iOS Home button icon
   keywords: "Wii U破解,wiiu破解,wiiu破解指南" #  the site keywords

uiux:
   android_chrome_color: "#1E90FF" #  the color of the Chrome address bar
   nprogress_color: "#1E90FF" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: false # meng

background:
   purecolor: "#eeeeee" # the background color

img:
   avatar: "https://s1.ax1x.com/2022/03/28/qD7Sdx.jpg" # your avatar

card:
   card_shadow: 1 # card shadow (0-24), 0 is not displayed
   card_hoverable: false # When the hover to deepen the shadow

many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: false
   googleplus: false
   weibo: true
   linkedin: false
   qq: true
   telegram: true

comment:
  used: "" # disqus,livere,gitment,valine
  # disqus config
  disqus_shortname: "" # Your disqus
  disqus_button: false # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: ''
  # gitment config
  owner: ""
  repo: ""
  client_id: ""
  client_secret: ""
  #valine config
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: "ヾﾉ≧∀≦)o来啊，快活啊!"

prism:
  themes: prism-okaidia
  components:
    - bash
  plugins:

mathjax: true

google_analytics: ""  # google analytics code

baidu_site_verification: ""  # baidu site verification code
google_site_verification: ""  # google search console verification code

baidu_auto_push: false  # if you used baidu auto push to commit links

lang: ""  # lang

deploy: "" # if you used coding pages

custom_css: "" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js
